dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decide-chris-prueba
  strategy: git
  api_key:
    secure: Yqgpb3a4E+On7paaG22/XXgQfMfedYZZXlGAXcs+wgI6IRUoYLijXxc3NBNevB4crO6wilV41xl5aLpArwzWAOg1Q8a8RD//DeP35B5EB84emnZgHeltSrNXmW3WXRkgUsj5UhjIRmUDay1ZYGipo5uqDPZrt9Q3b56LVBuhU0wDoun+AG6eLNRUUBLhO6zSFSexM1oCSidK7d2q4JBOTjaSn5Ok2PzjTCWRlg6ONkRnvPF8WANxsh/qvM/91bCBIrAkgWBou9lQ87VOmlnSTvRMYGXVhl0d5PfAm/9sWLqHEvlNq1pCai7De2rPuZ7Ije57qMIaXHBWTtZew/oIYk3jLgBflaELe5OSt5jhiAvtQd1cd91ky27mcBznvOjhoKviElTxAcB1TtEhb5H1OZbfSXcv8wblLMU1GgECw4KJYGaTPRMIVsjaPZXj2fWt+1hKVDQWilzueVrsp//RNEyxBURkGzdrArS7ibxCiW7mt4uzyUqFnZWtk0LBP34Kmw4byBTwJND1RBC5qS/477J3KcM1R1V8TNqMiD1f9zfA3olbfKOcCTvWdqukDKMH0pwM6qREfG1HsPOBhvRrER2tm/l+iRQzTaAIv/UiWZO+iW/BQoJYWRYjZxTDVdrS+T0RjYuTqAopK59TfFiyC4jSIwyhDhyULpeh9jAXP0A=
